Repository max2023-4th-project-01/BE-A-Cokkiri-Market, pull requests merged in 2023-09, with the labels that each got.

#11 feat: 2주차 리뷰 반영#10
  src/main/java/com/cokkiri/secondhand/global/auth/config/CorsConfig.java
  src/main/java/com/cokkiri/secondhand/global/auth/config/SecurityConfig.java
  src/main/java/com/cokkiri/secondhand/global/auth/controller/GeneralAuthController.java
  src/main/java/com/cokkiri/secondhand/global/auth/dto/request/GeneralLogInRequest.java
  src/main/java/com/cokkiri/secondhand/global/auth/dto/request/GeneralSignUpRequest.java
  src/main/java/com/cokkiri/secondhand/global/auth/dto/response/JwtTokenResponse.java
  src/main/java/com/cokkiri/secondhand/global/auth/entity/JwtAccessToken.java
  src/main/java/com/cokkiri/secondhand/global/auth/entity/JwtRefreshToken.java
  src/main/java/com/cokkiri/secondhand/global/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/cokkiri/secondhand/global/auth/infrastructure/JwtAuthHttpResponseManager.java
  src/main/java/com/cokkiri/secondhand/global/auth/infrastructure/JwtTokenGenerator.java
  src/main/java/com/cokkiri/secondhand/global/auth/infrastructure/MemoryJwtRepository.java
  src/main/java/com/cokkiri/secondhand/global/auth/service/GeneralAuthService.java
  src/main/java/com/cokkiri/secondhand/global/auth/service/JwtTokenService.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionHttpStatusCodeFactory.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionType.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/IllegalStatusException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/LoginFailureException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NicknameDuplicationException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotExistAccessTokenException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotExistRefreshTokenException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotFoundLocationException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotFoundUserByUsernameException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/UsernameDuplicationException.java
  src/main/java/com/cokkiri/secondhand/item/controller/ItemController.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemService.java
  src/main/java/com/cokkiri/secondhand/user/entity/GeneralUser.java
  src/main/java/com/cokkiri/secondhand/user/repository/GeneralUserJpaRepository.java
Labels: ✨ Feat

#13 feat: 동네 관련 API 추가#12
  src/main/java/com/cokkiri/secondhand/global/auth/config/SecurityConfig.java
  src/main/java/com/cokkiri/secondhand/global/auth/entity/UserInfoForJwt.java
  src/main/java/com/cokkiri/secondhand/global/auth/service/GeneralAuthService.java
  src/main/java/com/cokkiri/secondhand/global/auth/service/OAuthService.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionHttpStatusCodeFactory.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionType.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/DuplicateMyLocationException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/LimitExceededMyLocationException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/MyLocationDeletionNotAllowedException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotFoundLocationException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotFoundMyLocationException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotFoundUserException.java
  src/main/java/com/cokkiri/secondhand/item/controller/LocationController.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/LocationNameListResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/LocationNameResponse.java
  src/main/java/com/cokkiri/secondhand/item/entity/Location.java
  src/main/java/com/cokkiri/secondhand/item/repository/LocationJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/repository/LocationSearchJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/service/LocationSearchService.java
  src/main/java/com/cokkiri/secondhand/user/controller/MyLocationController.java
  src/main/java/com/cokkiri/secondhand/user/dto/request/AddMyLocationRequest.java
  src/main/java/com/cokkiri/secondhand/user/dto/response/MyLocationListResponse.java
  src/main/java/com/cokkiri/secondhand/user/dto/response/MyLocationResponse.java
  src/main/java/com/cokkiri/secondhand/user/entity/GeneralUser.java
  src/main/java/com/cokkiri/secondhand/user/entity/MyLocation.java
  src/main/java/com/cokkiri/secondhand/user/repository/MyLocationJpaRepository.java
  src/main/java/com/cokkiri/secondhand/user/repository/UserEntityJpaRepository.java
  src/main/java/com/cokkiri/secondhand/user/service/MyLocationService.java
  src/main/resources/application-common.yml
  src/main/resources/data.sql
  src/test/java/com/cokkiri/secondhand/ApiTest.java
  src/test/java/com/cokkiri/secondhand/user/controller/MyLocationControllerTest.java
Labels: ✨ Feat

#14 fix: 잘못 올라간 파일 삭제#12
  src/main/resources/application-common.yml
Labels: 🐞 Fix

#16 feat: 카테고리 목록 불러오기 api 추가#15
  src/main/java/com/cokkiri/secondhand/item/controller/CategoryController.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/CategoryListResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/CategoryResponse.java
  src/main/java/com/cokkiri/secondhand/item/entity/Category.java
  src/main/java/com/cokkiri/secondhand/item/repository/CategoryJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/service/CategoryService.java
Labels: ✨ Feat

#18 feat: 아이템 목록 불러오기 api 추가 작업#8
  build.gradle
  src/main/java/com/cokkiri/secondhand/global/auth/config/SecurityConfig.java
  src/main/java/com/cokkiri/secondhand/global/auth/entity/UserInfoForJwt.java
  src/main/java/com/cokkiri/secondhand/global/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/cokkiri/secondhand/global/auth/infrastructure/JwtAuthHttpResponseManager.java
  src/main/java/com/cokkiri/secondhand/global/auth/infrastructure/JwtTokenGenerator.java
  src/main/java/com/cokkiri/secondhand/global/auth/service/GeneralAuthService.java
  src/main/java/com/cokkiri/secondhand/global/auth/service/OAuthService.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionHttpStatusCodeFactory.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionType.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/EmptyMyLocationListException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotExistSelectedMyLocationException.java
  src/main/java/com/cokkiri/secondhand/item/controller/ItemController.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemListResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemResponse.java
  src/main/java/com/cokkiri/secondhand/item/entity/Item.java
  src/main/java/com/cokkiri/secondhand/item/entity/ItemStatus.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemDslRepository.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemDslRepositoryImpl.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemService.java
  src/main/java/com/cokkiri/secondhand/user/entity/GeneralUser.java
  src/main/java/com/cokkiri/secondhand/user/entity/MyLocation.java
  src/main/java/com/cokkiri/secondhand/user/entity/MyLocationList.java
  src/main/java/com/cokkiri/secondhand/user/entity/UserEntity.java
  src/main/java/com/cokkiri/secondhand/user/entity/UserType.java
  src/main/java/com/cokkiri/secondhand/user/repository/MyLocationJpaRepository.java
  src/main/java/com/cokkiri/secondhand/user/service/MyLocationService.java
  src/main/resources/data.sql
  src/test/java/com/cokkiri/secondhand/user/controller/MyLocationControllerTest.java
Labels: ✨ Feat

#19 워크플로우 정의 파일 작성
  .github/workflows/deploy.yml
  src/main/java/com/cokkiri/secondhand/user/entity/UserEntity.java
Labels: 🌏 Deploy

#23 feat: 3주차 리뷰 반영
  src/main/java/com/cokkiri/secondhand/item/repository/CategoryJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemDslRepositoryImpl.java
  src/main/java/com/cokkiri/secondhand/item/repository/LocationJpaRepository.java
  src/main/java/com/cokkiri/secondhand/user/entity/UserType.java
  src/main/java/com/cokkiri/secondhand/user/repository/UserEntityJpaRepository.java
  src/main/java/com/cokkiri/secondhand/user/service/MyLocationService.java
  src/test/java/com/cokkiri/secondhand/user/controller/MyLocationControllerTest.java
Labels: 🔨 Refactor

#25 feat: 카테고리 추천 목록 불러오기 api 추가#24
  src/main/java/com/cokkiri/secondhand/item/controller/CategoryController.java
  src/main/java/com/cokkiri/secondhand/item/service/CategoryService.java
Labels: ✨ Feat

#27 feat: 아이템 상세정보 불러오기 api 임시 추가#26
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionHttpStatusCodeFactory.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionType.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotFoundItemException.java
  src/main/java/com/cokkiri/secondhand/item/controller/ItemController.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemDetailResponse.java
  src/main/java/com/cokkiri/secondhand/item/entity/Item.java
  src/main/java/com/cokkiri/secondhand/item/entity/ItemContent.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemService.java
  src/main/resources/data.sql
Labels: ✨ Feat

#29 feat: 중고 거래 아이템 조회수, 좋아요 기능 구현#28
  src/main/java/com/cokkiri/secondhand/global/auth/config/SecurityConfig.java
  src/main/java/com/cokkiri/secondhand/item/controller/ItemController.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/CountDataResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemFavoriteResponse.java
  src/main/java/com/cokkiri/secondhand/item/entity/Favorite.java
  src/main/java/com/cokkiri/secondhand/item/entity/HitHistory.java
  src/main/java/com/cokkiri/secondhand/item/entity/HitHistoryList.java
  src/main/java/com/cokkiri/secondhand/item/entity/Item.java
  src/main/java/com/cokkiri/secondhand/item/entity/ItemContent.java
  src/main/java/com/cokkiri/secondhand/item/entity/ItemMetadata.java
  src/main/java/com/cokkiri/secondhand/item/repository/FavoriteJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemMetadataJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/repository/MemoryItemHitCountRepository.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemMetadataService.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemService.java
Labels: ✨ Feat

#31 feat: 판매자 아이템 목록 불러오기 api 임시 추가#30
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotFoundUserException.java
  src/main/java/com/cokkiri/secondhand/item/controller/ItemController.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemFavoriteResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemForUserResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemListForUserResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemStatusListResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemStatusResponse.java
  src/main/java/com/cokkiri/secondhand/item/entity/Status.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemDslRepository.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemDslRepositoryImpl.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemService.java
  src/main/java/com/cokkiri/secondhand/user/repository/UserEntityJpaRepository.java
  src/main/resources/data.sql
Labels: ✨ Feat

#32 fix: 중고거래 조회 여부 체크 로직 수정#28
  src/main/java/com/cokkiri/secondhand/item/entity/HitHistoryList.java
Labels: ✨ Feat

#35 4주차 리뷰 반영
  src/main/java/com/cokkiri/secondhand/global/auth/infrastructure/MemoryJwtRepository.java
  src/main/java/com/cokkiri/secondhand/global/exception/GlobalExceptionHandler.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemFavoriteResponse.java
  src/main/java/com/cokkiri/secondhand/item/entity/Status.java
  src/main/java/com/cokkiri/secondhand/item/repository/CategoryDslRepository.java
  src/main/java/com/cokkiri/secondhand/item/repository/CategoryDslRepositoryImpl.java
  src/main/java/com/cokkiri/secondhand/item/repository/CategoryJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemDslRepositoryImpl.java
  src/main/java/com/cokkiri/secondhand/item/repository/MemoryItemHitCountRepository.java
  src/main/java/com/cokkiri/secondhand/item/service/CategoryService.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemMetadataService.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemService.java
  src/main/java/com/cokkiri/secondhand/user/dto/response/MyLocationResponse.java
Labels: 🔨 Refactor

#43 feat: 회원 가입시 프로필 이미지 업로드 추가#38
  .gitignore
  build.gradle
  src/main/java/com/cokkiri/secondhand/global/auth/config/AwsS3Config.java
  src/main/java/com/cokkiri/secondhand/global/auth/controller/GeneralAuthController.java
  src/main/java/com/cokkiri/secondhand/global/auth/service/GeneralAuthService.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionHttpStatusCodeFactory.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionType.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/FileUploadFailureException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/IllegalFileStateException.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotExistFileException.java
  src/main/java/com/cokkiri/secondhand/global/image/infrastructure/ImageType.java
  src/main/java/com/cokkiri/secondhand/global/image/infrastructure/ImageUploader.java
  src/main/java/com/cokkiri/secondhand/global/image/infrastructure/S3ImageUploaderImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: ✨ Feat

#45 아이템 목록 불러오기 미구현 부분 추가#30
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionHttpStatusCodeFactory.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionType.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/NotFoundCategoryException.java
  src/main/java/com/cokkiri/secondhand/item/controller/ItemController.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/CountDataResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemForAnyOneListResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemForSpecificUserListResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemForUserResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemResponseForAnyOne.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemResponseForSpecificUser.java
  src/main/java/com/cokkiri/secondhand/item/entity/Item.java
  src/main/java/com/cokkiri/secondhand/item/entity/ItemImage.java
  src/main/java/com/cokkiri/secondhand/item/repository/CategoryJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemService.java
  src/main/resources/data.sql
Labels: ✨ Feat

#46 아이템 상세 정보 불러오기 미구현 부분 추가#26
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemDetailResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemImageResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemStatusListResponse.java
  src/main/java/com/cokkiri/secondhand/item/dto/response/ItemStatusResponse.java
  src/main/java/com/cokkiri/secondhand/item/entity/Item.java
  src/main/java/com/cokkiri/secondhand/item/entity/ItemStatus.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemStatusJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemService.java
Labels: ✨ Feat

#48 fix: 조회수, 좋아요 수 증감 로직의 락 방식을 Optimistic Lock으로 변경#47
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionHttpStatusCodeFactory.java
  src/main/java/com/cokkiri/secondhand/global/exception/CustomExceptionType.java
  src/main/java/com/cokkiri/secondhand/global/exception/list/FavoriteCountFailureException.java
  src/main/java/com/cokkiri/secondhand/item/entity/ItemMetadata.java
  src/main/java/com/cokkiri/secondhand/item/repository/ItemMetadataJpaRepository.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemMetadataService.java
  src/main/java/com/cokkiri/secondhand/item/service/ItemService.java
Labels: 🐞 Fix
